version: '3.8'
services: 
  apache: # service name (unique)
    image: php:7.2-apache    
    labels: 
      - "traefik.http.routers.apache.rule=Host(`apache.app.test`)"
      - "traefik.http.routers.apache.entrypoints=websecurity" #Para forzar el uso de HTTPS y certificados
      - "traefik.http.routers.apache.tls.certresolver=myresolver" #Para forzar el uso de HTTPS y certificados
    volumes: 
      - ./php/:/var/www/html
    networks: 
      traefik_network:
networks: 
  traefik_network:
    name: traefik_net
    driver: bridge
